version: '2'
services:
  web:
    build: .
    container_name: node
    command: npm start
    ports:
     - "3000:3000"
    environment:
     - NODE_ENV=development
    volumes:
     - ./src:/src
     - ./dist:/dist
     - ./downloads:/data/downloads
    depends_on:
     - mongo
  rockmongo:
    image: javierjeronimo/rockmongo
    container_name: rockmongo
    ports:
     - 8080:80
    depends_on:
     - mongo
  mongo:
    image: mongo:3.2
    container_name: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - ./db:/data/db
