version: '2'
services:
  web:
    build: .
    container_name: node
    command: npm start
    ports:
     - "3000:3000"
    environment:
     - NODE_ENV=development
    volumes:
     - ./app:/src/app
    depends_on:
     - db
  db:
    image: mongo:3.2
    container_name: db_1
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - ./db:/data/db
