web:
  build: .
  container_name: meanjs
  command: npm start
  links:
   - db
  ports:
   - "3000:3000"
  environment:
   - NODE_ENV=development
  volumes:
   - ./app:/src/app
db:
  image: mongo:3.2
  container_name: db_1
  restart: always
  ports:
   - "27017:27017"
  volumes:
   - db:/data/db
